apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodered-tekton
  name: nodered-tekton
spec:
  ports:
    - name: 1880-tcp
      port: 1880
      targetPort: 1880
      protocol: TCP
  selector:
    app: nodered-tekton
